In [3]:
import numpy as np

In [8]:
arr=np.random.randint(1,100,(10,10))
arr

array([[69, 57,  9, 94, 84, 20, 65, 32, 98, 14],
       [51, 64,  2, 83, 11, 12, 10, 39,  3, 29],
       [ 5, 14, 64, 35, 53, 41, 83, 77,  6, 83],
       [19, 12, 18, 28, 16, 84, 47, 48,  7, 90],
       [58, 91, 83, 75, 66,  2, 54, 71, 67, 39],
       [23, 53, 89, 71,  7, 19,  2, 39, 29, 66],
       [74, 16, 66, 46, 62,  6, 63, 36, 15, 26],
       [54, 35, 89, 50, 72, 51, 84, 44,  4, 51],
       [73, 83, 45, 75, 46, 10, 98, 98, 40, 33],
       [63, 32, 13, 77, 20, 37, 42, 34, 97, 99]])

# Slicing 

In [9]:
arr


array([[69, 57,  9, 94, 84, 20, 65, 32, 98, 14],
       [51, 64,  2, 83, 11, 12, 10, 39,  3, 29],
       [ 5, 14, 64, 35, 53, 41, 83, 77,  6, 83],
       [19, 12, 18, 28, 16, 84, 47, 48,  7, 90],
       [58, 91, 83, 75, 66,  2, 54, 71, 67, 39],
       [23, 53, 89, 71,  7, 19,  2, 39, 29, 66],
       [74, 16, 66, 46, 62,  6, 63, 36, 15, 26],
       [54, 35, 89, 50, 72, 51, 84, 44,  4, 51],
       [73, 83, 45, 75, 46, 10, 98, 98, 40, 33],
       [63, 32, 13, 77, 20, 37, 42, 34, 97, 99]])

In [10]:
arr[2:5]

array([[ 5, 14, 64, 35, 53, 41, 83, 77,  6, 83],
       [19, 12, 18, 28, 16, 84, 47, 48,  7, 90],
       [58, 91, 83, 75, 66,  2, 54, 71, 67, 39]])

In [11]:
arr[0:-1]

array([[69, 57,  9, 94, 84, 20, 65, 32, 98, 14],
       [51, 64,  2, 83, 11, 12, 10, 39,  3, 29],
       [ 5, 14, 64, 35, 53, 41, 83, 77,  6, 83],
       [19, 12, 18, 28, 16, 84, 47, 48,  7, 90],
       [58, 91, 83, 75, 66,  2, 54, 71, 67, 39],
       [23, 53, 89, 71,  7, 19,  2, 39, 29, 66],
       [74, 16, 66, 46, 62,  6, 63, 36, 15, 26],
       [54, 35, 89, 50, 72, 51, 84, 44,  4, 51],
       [73, 83, 45, 75, 46, 10, 98, 98, 40, 33]])

In [12]:
arr[-4:-1]

array([[74, 16, 66, 46, 62,  6, 63, 36, 15, 26],
       [54, 35, 89, 50, 72, 51, 84, 44,  4, 51],
       [73, 83, 45, 75, 46, 10, 98, 98, 40, 33]])

In [13]:
arr[:-1]

array([[69, 57,  9, 94, 84, 20, 65, 32, 98, 14],
       [51, 64,  2, 83, 11, 12, 10, 39,  3, 29],
       [ 5, 14, 64, 35, 53, 41, 83, 77,  6, 83],
       [19, 12, 18, 28, 16, 84, 47, 48,  7, 90],
       [58, 91, 83, 75, 66,  2, 54, 71, 67, 39],
       [23, 53, 89, 71,  7, 19,  2, 39, 29, 66],
       [74, 16, 66, 46, 62,  6, 63, 36, 15, 26],
       [54, 35, 89, 50, 72, 51, 84, 44,  4, 51],
       [73, 83, 45, 75, 46, 10, 98, 98, 40, 33]])

In [14]:
arr[4:]

array([[58, 91, 83, 75, 66,  2, 54, 71, 67, 39],
       [23, 53, 89, 71,  7, 19,  2, 39, 29, 66],
       [74, 16, 66, 46, 62,  6, 63, 36, 15, 26],
       [54, 35, 89, 50, 72, 51, 84, 44,  4, 51],
       [73, 83, 45, 75, 46, 10, 98, 98, 40, 33],
       [63, 32, 13, 77, 20, 37, 42, 34, 97, 99]])

In [16]:
arr


array([[69, 57,  9, 94, 84, 20, 65, 32, 98, 14],
       [51, 64,  2, 83, 11, 12, 10, 39,  3, 29],
       [ 5, 14, 64, 35, 53, 41, 83, 77,  6, 83],
       [19, 12, 18, 28, 16, 84, 47, 48,  7, 90],
       [58, 91, 83, 75, 66,  2, 54, 71, 67, 39],
       [23, 53, 89, 71,  7, 19,  2, 39, 29, 66],
       [74, 16, 66, 46, 62,  6, 63, 36, 15, 26],
       [54, 35, 89, 50, 72, 51, 84, 44,  4, 51],
       [73, 83, 45, 75, 46, 10, 98, 98, 40, 33],
       [63, 32, 13, 77, 20, 37, 42, 34, 97, 99]])

In [15]:
arr[0:6:2]

array([[69, 57,  9, 94, 84, 20, 65, 32, 98, 14],
       [ 5, 14, 64, 35, 53, 41, 83, 77,  6, 83],
       [58, 91, 83, 75, 66,  2, 54, 71, 67, 39]])

In [17]:
arr[-1:-8:-3]

array([[63, 32, 13, 77, 20, 37, 42, 34, 97, 99],
       [74, 16, 66, 46, 62,  6, 63, 36, 15, 26],
       [19, 12, 18, 28, 16, 84, 47, 48,  7, 90]])

In [20]:
arr[2:-1:2]

array([[ 5, 14, 64, 35, 53, 41, 83, 77,  6, 83],
       [58, 91, 83, 75, 66,  2, 54, 71, 67, 39],
       [74, 16, 66, 46, 62,  6, 63, 36, 15, 26],
       [73, 83, 45, 75, 46, 10, 98, 98, 40, 33]])

In [22]:
arr[::-1]

array([[63, 32, 13, 77, 20, 37, 42, 34, 97, 99],
       [73, 83, 45, 75, 46, 10, 98, 98, 40, 33],
       [54, 35, 89, 50, 72, 51, 84, 44,  4, 51],
       [74, 16, 66, 46, 62,  6, 63, 36, 15, 26],
       [23, 53, 89, 71,  7, 19,  2, 39, 29, 66],
       [58, 91, 83, 75, 66,  2, 54, 71, 67, 39],
       [19, 12, 18, 28, 16, 84, 47, 48,  7, 90],
       [ 5, 14, 64, 35, 53, 41, 83, 77,  6, 83],
       [51, 64,  2, 83, 11, 12, 10, 39,  3, 29],
       [69, 57,  9, 94, 84, 20, 65, 32, 98, 14]])

In [27]:
arr[3,4]

16

In [28]:
arr

array([[69, 57,  9, 94, 84, 20, 65, 32, 98, 14],
       [51, 64,  2, 83, 11, 12, 10, 39,  3, 29],
       [ 5, 14, 64, 35, 53, 41, 83, 77,  6, 83],
       [19, 12, 18, 28, 16, 84, 47, 48,  7, 90],
       [58, 91, 83, 75, 66,  2, 54, 71, 67, 39],
       [23, 53, 89, 71,  7, 19,  2, 39, 29, 66],
       [74, 16, 66, 46, 62,  6, 63, 36, 15, 26],
       [54, 35, 89, 50, 72, 51, 84, 44,  4, 51],
       [73, 83, 45, 75, 46, 10, 98, 98, 40, 33],
       [63, 32, 13, 77, 20, 37, 42, 34, 97, 99]])

In [29]:
arr[2,6:2,6]

IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed