In [1]:
pip install numpy


Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np
np

<module 'numpy' from 'C:\\Users\\adder\\anaconda3\\Lib\\site-packages\\numpy\\__init__.py'>

In [3]:
np.__version__

'1.26.4'

In [4]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [5]:
np.arange(10,20,5)

array([10, 15])

In [9]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [10]:
np.zeros((3,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [14]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [19]:
np.ones((3,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [20]:
np.ones((2,2),dtype=int)

array([[1, 1],
       [1, 1]])

In [15]:
random.rand(5)

NameError: name 'random' is not defined

In [16]:
np.random.rand(5)

array([0.78290643, 0.04469293, 0.84234468, 0.79633356, 0.6619151 ])

In [18]:
np.random.rand(5)

array([0.61192333, 0.58090961, 0.00377935, 0.2179447 , 0.84560781])

In [23]:
np.random.randint(2,10,5)

array([4, 9, 7, 4, 7])

In [24]:
np.random.randint(2,10,5)

array([4, 2, 5, 2, 3])

In [26]:
np.random.rand(2,2)

array([[0.89943005, 0.30554072],
       [0.38574575, 0.27930877]])

In [28]:
np.random.randint(2,10)

7

In [29]:
np.random.randint(2,10,4)

array([2, 4, 5, 3])

In [30]:
np.random.randint(2,40,(10,10))

array([[34,  5, 17,  6, 34, 23, 25, 10, 25, 15],
       [17, 12, 13, 32,  5, 27, 12, 25, 31,  9],
       [33, 14, 24, 10, 19, 20, 18, 18, 38, 21],
       [ 4, 16, 19,  3, 19, 36, 26, 33, 27, 24],
       [35, 13, 35, 12,  4, 39, 37,  4, 13, 24],
       [ 7, 21, 32, 39, 37, 22, 32,  8, 23, 29],
       [24,  7, 36, 35, 16, 34, 11, 25, 24,  7],
       [13,  6,  2, 29,  5, 14, 25, 24, 16, 29],
       [31, 29, 19, 28, 31, 37,  3, 23, 25, 33],
       [17, 12, 39, 29, 11, 10, 31, 39, 39, 25]])

In [32]:
np.random.randint(4,5)

4

In [33]:
np.arange(3,12)

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11])

In [39]:
np.arange(3,12).reshape(3,3)

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [43]:
np.arange(0,25).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [55]:
b=np.arange(0,25)

In [56]:
b.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [54]:
b.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [58]:
b=np.arange(0,25).reshape(5,5)

In [59]:
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [60]:
type(b)

numpy.ndarray

In [61]:
b[3:3]

array([], shape=(0, 5), dtype=int32)

In [62]:
b[:]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [63]:
b[2:2]

array([], shape=(0, 5), dtype=int32)